import type { Metadata } from "next";
import { notFound } from "next/navigation";
import AdminShell from "@/components/admin/AdminShell";
import { getPayroll } from "@/lib/queries";
import PrintButton from "@/components/payroll/PrintButton";

export const metadata: Metadata = { title: "Payslip · Ukuu HR" };

export default async function PayslipPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const res = await getPayroll();
  const run = res.data.find((r) => r.id === id);
  if (!run) notFound();
  const item = run.items[0];

  const rows = item
    ? [
        ["Basic Salary", item.gross - item.overtimePay],
        ["Overtime Pay", item.overtimePay],
        ["Gross Pay", item.gross],
        ["NAPSA (5%)", -item.nAPSA],
        ["NHIMA (1%)", -item.nhima],
        ["PAYE", -item.paye],
        ["Net Pay", item.net],
      ]
    : [];

  return (
    <AdminShell activeKey="payroll">
      <div className="bk-admin-section-header">
        <div className="bk-admin-section-header-left">
          <div className="bk-admin-greeting">Payroll · {run.periodLabel}</div>
          <h1 className="bk-admin-h1">Payslip</h1>
          <p className="bk-admin-sub">{item ? item.employeeName : "No items in this run"} · {item?.employeeCode}</p>
        </div>
        <div className="bk-admin-actions"><PrintButton /></div>
      </div>

      <div className="bk-admin-card" style={{ maxWidth: 640 }}>
        <div className="bk-admin-card-header" style={{ justifyContent: "flex-start", gap: 14 }}>
          <span className="bk-admin-sidebar-brand-logo"><img src="/ukuu-brand-white.png" alt="Ukuu HR" /></span>
          <div>
            <div style={{ fontWeight: 800, fontSize: 16 }}>UKUU HR · UkuuHR Demo Ltd</div>
            <div className="bk-muted-text">Payslip · {run.periodLabel}</div>
          </div>
        </div>
        <div className="bk-admin-card-content">
          {!item && <div className="bk-admin-empty">No payslip available for this run.</div>}
          {item && (
            <>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 20 }}>
                <div><div className="bk-muted-text">Employee</div><div style={{ fontWeight: 700 }}>{item.employeeName}</div></div>
                <div><div className="bk-muted-text">Code</div><div className="bk-mono">{item.employeeCode}</div></div>
                <div><div className="bk-muted-text">Hours worked</div><div>{item.workedHours}h {item.overtimeHours > 0 ? `(+${item.overtimeHours}h OT)` : ""}</div></div>
                <div><div className="bk-muted-text">Period</div><div>{run.periodLabel}</div></div>
              </div>
              <table className="bk-admin-table">
                <thead><tr><th>Description</th><th style={{ textAlign: "right" }}>Amount (ZMW)</th></tr></thead>
                <tbody>
                  {rows.map(([label, amount]) => (
                    <tr key={label as string}>
                      <td style={{ fontWeight: label === "Net Pay" || label === "Gross Pay" ? 800 : 500 }}>{label}</td>
                      <td style={{ textAlign: "right", fontFamily: "var(--font-mono), monospace", fontWeight: label === "Net Pay" ? 900 : 600, color: (amount as number) < 0 ? "#DC2626" : "var(--bk-ink)" }}>
                        {(amount as number) < 0 ? `−${Math.abs(amount as number).toLocaleString()}` : (amount as number).toLocaleString()}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <div style={{ marginTop: 16, textAlign: "center", color: "var(--bk-ink-3)", fontSize: 11 }}>
                Generated by UKUU HR · statutory deductions follow ZRA 2025 PAYE, NAPSA &amp; NHIMA
              </div>
            </>
          )}
        </div>
      </div>
    </AdminShell>
  );
}